/**
 * bpmn-js 画布中文国际化。
 *
 * bpmn-js / diagram-js / properties-panel 的文案统一由注入的 `translate` 服务产出，
 * 这里用自定义模块覆盖该服务，把英文文案替换为中文。
 * 用法：把 default 导出的模块放进 BpmnJS 的 additionalModules（放在最后以覆盖内置实现）。
 *
 * 注意：词条键**区分大小写**，必须与 bpmn-js 源码中的原文完全一致
 * （例如是 'Create start event' 而不是 'Create Start Event'）。
 * 为避免大小写差异导致漏翻，customTranslate 额外做了不区分大小写的兜底匹配。
 */

const translations: Record<string, string> = {
  // ───────── 工具栏 Palette（键名取自 bpmn-js/lib/features/palette/PaletteProvider.js）─────────
  'Activate hand tool': '激活抓手工具',
  'Activate lasso tool': '激活套索工具',
  'Activate create/remove space tool': '激活创建/删除空间工具',
  'Activate global connect tool': '激活全局连接工具',
  'Create start event': '创建开始事件',
  'Create intermediate/boundary event': '创建中间/边界事件',
  'Create end event': '创建结束事件',
  'Create gateway': '创建网关',
  'Create task': '创建任务',
  'Create user task': '创建用户任务',
  'Create data object reference': '创建数据对象',
  'Create data store reference': '创建数据存储',
  'Create expanded sub-process': '创建展开的子流程',
  'Create pool/participant': '创建池/参与者',
  'Create group': '创建分组',
  'Create text annotation': '创建文本注解',

  // ───────── 右键菜单 Context Pad（取自 ContextPadProvider.js）─────────
  'Append end event': '追加结束事件',
  'Append gateway': '追加网关',
  'Append task': '追加任务',
  'Append user task': '追加用户任务',
  'Append receive task': '追加接收任务',
  'Append message intermediate catch event': '追加消息中间捕获事件',
  'Append timer intermediate catch event': '追加定时中间捕获事件',
  'Append conditional intermediate catch event': '追加条件中间捕获事件',
  'Append signal intermediate catch event': '追加信号中间捕获事件',
  'Append intermediate/boundary event': '追加中间/边界事件',
  'Append compensation activity': '追加补偿活动',
  'Add text annotation': '添加文本注解',
  'Connect to other element': '连接到其他元素',
  'Connect using association': '用关联连接',
  'Connect using data input association': '用数据输入关联连接',
  'Change element': '更改元素',
  'Add lane above': '在上方添加泳道',
  'Add lane below': '在下方添加泳道',
  'Divide into two lanes': '拆分为两条泳道',
  'Divide into three lanes': '拆分为三条泳道',
  Delete: '删除',
  Remove: '移除',

  // ───────── 替换菜单 Replace / 元素类型 ─────────
  'Replace with': '替换为',
  'Start Event': '开始事件',
  'Intermediate Throw Event': '中间抛出事件',
  'Intermediate Catch Event': '中间捕获事件',
  'End Event': '结束事件',
  'Boundary Event': '边界事件',
  Task: '任务',
  'User Task': '用户任务',
  'Service Task': '服务任务',
  'Send Task': '发送任务',
  'Receive Task': '接收任务',
  'Script Task': '脚本任务',
  'Business Rule Task': '业务规则任务',
  'Manual Task': '手工任务',
  'Call Activity': '调用活动',
  'Sub-process': '子流程',
  'Sub-process (collapsed)': '子流程（折叠）',
  'Sub-process (expanded)': '子流程（展开）',
  'Event Sub-process': '事件子流程',
  Transaction: '事务',
  'Exclusive Gateway': '排他网关',
  'Parallel Gateway': '并行网关',
  'Inclusive Gateway': '包容网关',
  'Complex Gateway': '复杂网关',
  'Event Based Gateway': '事件网关',
  Participant: '参与者',
  Pool: '池',
  Group: '分组',
  'Text Annotation': '文本注解',
  'Data Object': '数据对象',
  'Data Store Reference': '数据存储引用',
  'Sequence Flow': '顺序流',
  'Message Flow': '消息流',
  Association: '关联',

  // ───────── 通用操作 ─────────
  Undo: '撤销',
  Redo: '重做',
  'Zoom in': '放大',
  'Zoom out': '缩小',
  'Zoom to fit': '自适应缩放',
  'Zoom to actual size': '实际大小',
  'Reset zoom': '重置缩放',
  'Align elements': '对齐元素',
  'Align elements left': '左对齐',
  'Align elements right': '右对齐',
  'Align elements top': '顶部对齐',
  'Align elements bottom': '底部对齐',
  'Align elements center': '垂直居中对齐',
  'Align elements middle': '水平居中对齐',
  'Distribute elements horizontally': '水平等距分布',
  'Distribute elements vertically': '垂直等距分布',
  'Move element': '移动元素',
  'Resize element': '调整元素大小',
  'Show mini-map': '显示缩略图',
  'Hide mini-map': '隐藏缩略图',
  'Select element': '选择元素',
  'Direct editing': '直接编辑',
  'Copy element': '复制元素',
  'Paste element': '粘贴元素',

  // ───────── 属性面板分组 / 常用项 ─────────
  General: '常规',
  Documentation: '文档',
  Id: '编号',
  ID: '编号',
  Name: '名称',
  Process: '流程',
  'Process Id': '流程编号',
  'Process ID': '流程编号',
  'Process Name': '流程名称',
  'Process name': '流程名称',
  'Version Tag': '版本标签',
  'Version tag': '版本标签',
  'versionTag': '版本标签',
  Version: '版本',
  Executable: '可执行',
  Properties: '属性',
  'Extension Properties': '扩展属性',
  'Extension properties': '扩展属性',
  'Extension Elements': '扩展元素',
  'Execution Listeners': '执行监听器',
  'Execution listeners': '执行监听器',
  'Asynchronous Continuations': '异步延续',
  'Asynchronous continuations': '异步延续',
  'Asynchronous Before': '前置异步',
  'Asynchronous before': '前置异步',
  'Asynchronous After': '后置异步',
  'Asynchronous after': '后置异步',
  Exclusive: '独占',
  'Job Configuration': '作业配置',
  'Job Priority': '作业优先级',
  'Job priority': '作业优先级',
  'Job execution': '作业执行',
  'Job type': '作业类型',
  'Job worker': '作业处理器',
  'Retry Time Cycle': '重试周期',
  'Retry time cycle': '重试周期',
  Retries: '重试',
  'Candidate Starter Configuration': '候选启动者配置',
  'Candidate Starter Groups': '候选启动组',
  'Candidate Starter Users': '候选启动用户',
  'Candidate starter': '候选发起人',
  'Candidate starter groups': '候选启动组',
  'Candidate starter users': '候选启动用户',
  Forms: '表单',
  Form: '表单',
  'Form Key': '表单标识',
  'Form key': '表单标识',
  'Form fields': '表单字段',
  'Form Fields': '表单字段',
  'Form reference': '表单引用',
  'Form Reference': '表单引用',
  'Form ID': '表单 ID',
  'Custom form key': '自定义表单标识',
  'Form JSON configuration': '表单 JSON 配置',
  'External form reference': '外部表单引用',
  'Camunda Form': 'Camunda 表单',
  'Camunda Form (embedded)': 'Camunda 表单（内嵌）',
  'Camunda Form (linked)': 'Camunda 表单（链接）',
  'Camunda Forms': 'Camunda 表单',
  'Camunda user task': 'Camunda 用户任务',
  'Embedded or External Task Forms': '内嵌或外部任务表单',
  'Generated Task Forms': '生成任务表单',
  'Start event form documentation': '开始事件表单文档',
  'User task form documentation': '用户任务表单文档',
  Input: '输入',
  Output: '输出',
  'Input Data': '输入数据',
  'Output Data': '输出数据',
  Conditions: '条件',
  Condition: '条件',
  'Condition Expression': '条件表达式',
  'Condition expression': '条件表达式',
  'Condition events': '条件事件',
  'Conditions documentation': '条件文档',
  'Conditional event documentation': '条件事件文档',
  Timer: '定时器',
  'Timer Definition': '定时器定义',
  'Timer Definition Type': '定时器定义类型',
  'Timer documentation': '定时器文档',
  'Documentation: Timer events': '文档：定时事件',
  'Documentation: Variable events': '文档：变量事件',
  'How to configure a timer': '如何配置定时器',
  'Cycle': '周期',
  'Duration': '时长',
  'Date': '日期',
  Message: '消息',
  'Message Reference': '消息引用',
  'Message reference': '消息引用',
  'Global message reference': '全局消息引用',
  'Message boundary event documentation': '消息边界事件文档',
  'Message catch event documentation': '消息捕获事件文档',
  'Message start event documentation': '消息开始事件文档',
  'Message throw event documentation': '消息抛出事件文档',
  'Message variable': '消息变量',
  Signal: '信号',
  'Signal Reference': '信号引用',
  'Signal reference': '信号引用',
  'Global signal reference': '全局信号引用',
  Error: '错误',
  'Error Reference': '错误引用',
  'Error reference': '错误引用',
  'Global error reference': '全局错误引用',
  'Errors': '错误',
  'Error event documentation': '错误事件文档',
  Escalation: '升级',
  'Escalation Reference': '升级引用',
  'Escalation reference': '升级引用',
  'Global escalation reference': '全局升级引用',
  Compensation: '补偿',
  'Start Initiator': '启动发起人',
  'Start initiator': '启动发起人',
  Initiator: '发起人',
  'History Time To Live': '历史数据保留时长',
  'History cleanup': '历史清理',
  'Time to live': '存活时间',
  'External Task Configuration': '外部任务配置',
  'External Task Topic': '外部任务主题',
  'External Task Priority': '外部任务优先级',
  'External task': '外部任务',
  'External resource': '外部资源',
  'External Resource': '外部资源',
  Connectors: '连接器',
  Connector: '连接器',
  'Connector ID': '连接器 ID',
  'Connector inputs': '连接器输入',
  'Connector outputs': '连接器输出',
  'Multi Instance': '多实例',
  'Multi-instance': '多实例',
  'Multi instance documentation': '多实例文档',
  'Element Documentation': '元素文档',
  'Element documentation': '元素文档',
  'Business Key': '业务键',
  'Business key': '业务键',
  'Business key expression': '业务键表达式',
  'Business ID': '业务 ID',
  'Business ID propagation documentation': '业务 ID 传播文档',
  'Task Listener': '任务监听器',
  'Task listeners': '任务监听器',
  'Task Listeners': '任务监听器',
  'Task listeners documentation': '任务监听器文档',
  'Task Priority': '任务优先级',
  'Task priority': '任务优先级',
  'Task definition': '任务定义',
  'Tasklist': '任务列表',
  'Startable': '可启动',
  'Is startable in tasklist': '可在任务列表启动',
  'Cannot start in tasklist': '不可在任务列表启动',
  Assignee: '办理人',
  'Candidate Users': '候选用户',
  'Candidate users': '候选用户',
  'Candidate Groups': '候选组',
  'Candidate groups': '候选组',
  'Due Date': '到期日',
  'Due date': '到期日',
  'Follow Up Date': '跟进日期',
  'Follow up date': '跟进日期',
  'User Assignment': '用户分配',
  'User assignment': '用户分配',
  'User task documentation': '用户任务文档',
  'User task priority documentation': '用户任务优先级文档',
  Scripts: '脚本',
  Script: '脚本',
  'Script Format': '脚本格式',
  'Script format': '脚本格式',
  'Script Type': '脚本类型',
  'Script type': '脚本类型',
  'Script task documentation': '脚本任务文档',
  'Inline Script': '内联脚本',
  'Inline script': '内联脚本',
  Resource: '资源',
  'Field Injections': '字段注入',
  'Field injections': '字段注入',
  'Field injection': '字段注入',
  'Add Property': '添加属性',
  'Add Entry': '添加条目',
  'Remove Entry': '删除条目',
  'Add input': '添加输入',
  'Add output': '添加输出',
  'Add documentation': '添加文档',
  'No documentation': '暂无文档',
  'No properties to display': '没有可显示的属性',
  'Specify a name': '请输入名称',
  'Specify an id': '请输入编号',
  'Select an element to edit its properties.': '请选中单个元素后再编辑其属性',
  'Multiple elements are selected. Select a single element to edit its properties.':
    '已选中多个元素，请只选中单个元素后再编辑其属性',

  // ───────── Camunda 平台属性面板分组名 ─────────
  Assignment: '分配',
  'Assignment type': '分配类型',
  Form: '表单',
  'Task listeners': '任务监听器',
  'Multi-instance': '多实例',
  Condition: '条件',
  'External task': '外部任务',
  Other: '其他',
  Config: '配置',

  // ───────── 多实例 / 通用字段 ─────────
  Sequential: '串行',
  Parallel: '并行',
  Collection: '集合',
  'Element variable': '元素变量',
  'Completion condition': '完成条件',
  'Completion': '完成',
  'Cardinality': '基数',
  'Loop cardinality': '循环基数',
  Priority: '优先级',
  'Candidate starter': '候选发起人',
  'Cancel remaining instances': '取消剩余实例',

  // ───────── 输入输出 / 监听器 / 字段注入 ─────────
  'Input/Output': '输入/输出',
  Inputs: '输入',
  Outputs: '输出',
  'In mappings': '输入映射',
  'Out mappings': '输出映射',
  'Input mapping': '输入映射',
  'Output mapping': '输出映射',
  'Input mappings documentation': '输入映射文档',
  'Output mappings documentation': '输出映射文档',
  'Input propagation': '输入传播',
  'Output propagation': '输出传播',
  'In mapping propagation': '输入映射传播',
  'Out mapping propagation': '输出映射传播',
  'Input collection': '输入集合',
  'Output collection': '输出集合',
  'Input element': '输入元素',
  'Output element': '输出元素',
  'To collect the output define the output collection and the output element expressions. ':
    '要收集输出，请定义输出集合和输出元素表达式。',
  'Add input mappings to control what is passed to the activity as local variables. ':
    '添加输入映射以控制作为局部变量传递给活动的内容。',
  'Add output mappings to control which variables are merged back into the process scope. ':
    '添加输出映射以控制哪些变量合并回流程作用域。',
  'Listener type': '监听器类型',
  'Listener ID': '监听器 ID',
  'Listener Type': '监听器类型',
  'Java class': 'Java 类',
  'Java Class': 'Java 类',
  Class: '类',
  'Delegate Class': '委托类',
  Expression: '表达式',
  'Delegate expression': '委托表达式',
  'Delegate Expression': '委托表达式',
  'Delegate Variable Mapping': '委托变量映射',
  'Field injection': '字段注入',
  'Field Injection': '字段注入',
  'Bind to': '绑定到',
  Binding: '绑定',
  'Local': '本地',
  'Script': '脚本',
  'Script Type': '脚本类型',
  'Inline Script': '内联脚本',
  'External Resource': '外部资源',
  'Create new ...': '新建……',
  'Create new list item': '新建列表项',
  'Create': '创建',
  'Delete item': '删除项',
  delete: '删除',
  update: '更新',
  'Toggle section': '切换分区',
  'Toggle list item': '切换列表项',

  // ───────── 事件 / 消息 / 信号 / 定时 等描述 ─────────
  'Event type': '事件类型',
  'Variable events': '变量事件',
  'Variable name': '变量名',
  'Variable assignment value': '变量赋值',
  'Variable events that trigger the condition evaluation. If none selected, all variable events will trigger the condition evaluation. ':
    '触发条件评估的变量事件。若未选择，所有变量事件都会触发条件评估。',
  'Specify the condition that triggers this event. ': '指定触发此事件的条件。',
  'Configure the message that the task waits for. ': '配置该任务等待的消息。',
  'Configure the message that this event waits for. ': '配置该事件等待的消息。',
  'Configure the message that will start this process instance. ': '配置将启动此流程实例的消息。',
  'Configure the message that will trigger this boundary event. ': '配置将触发此边界事件的消息。',
  'Message': '消息',
  'Subscription correlation key': '订阅关联键',
  'Subscription correlation key documentation': '订阅关联键文档',
  'Identifier computed from the process context that is used to correlate an incoming message (e.g. ':
    '根据流程上下文计算、用于关联传入消息的标识符（例如 ',
  'Specify which job workers handle the event work. ': '指定由哪个作业处理器处理事件工作。',
  'Specify which job workers handle the task work to evaluate business rules. ':
    '指定由哪个作业处理器处理评估业务规则的任务工作。',
  'Specify which job workers handle the task work to execute a script. ':
    '指定由哪个作业处理器处理执行脚本的任务工作。',
  'Specify which job workers handle the task work to execute a service (e.g. ':
    '指定由哪个作业处理器处理执行服务（如 ',
  'Specify which job workers handle the task work to send a message (e.g. ':
    '指定由哪个作业处理器处理发送消息的任务工作（如 ',
  'React to user task lifecycle events by executing a job worker. ':
    '通过执行作业处理器来响应户任务生命周期事件。',
  'Evaluate a business rule, for example a DMN decision. To add a custom implementation, use a job worker. ':
    '评估业务规则，例如 DMN 决策。要添加自定义实现，请使用作业处理器。',
  'Implement a script task using an inline FEEL expression. To add a custom implementation, use a job worker. ':
    '使用内联 FEEL 表达式实现脚本任务。要添加自定义实现，请使用作业处理器。',
  'Implement a user task managed by Camunda. To add a custom implementation, use a job worker. ':
    '实现由 Camunda 管理的用户任务。要添加自定义实现，请使用作业处理器。',
  'Implement the ad-hoc subprocess as a job worker instead of activating inner elements. The job type determines which worker handles the subprocess execution. ':
    '将即席子流程实现为作业处理器，而非激活内部元素。作业类型决定由哪个处理器处理子流程执行。',
  'Execute this task for each element of a given collection. ': '对给定集合中的每个元素执行此任务。',
  'Define the assignment, schedule, and priority of the user task. Assignee, candidate groups, and candidate users can be combined. Use due date and follow-up date to express deadlines and urgency. ':
    '定义用户任务的分配、计划和优先级。办理人、候选组和候选用户可组合使用。使用到期日和跟进日期表示截止时间和紧急程度。',
  'Define the completion behavior of an ad-hoc subprocess. If no completion condition is set, it will be completed after all active elements have been completed. ':
    '定义即席子流程的完成行为。若未设置完成条件，将在所有活动元素完成后完成。',
  'Define the decision to evaluate and how to map back the evaluation result. ':
    '定义要评估的决策以及如何将评估结果映射回去。',
  'Define the error to catch. Specify an error code (e.g. ': '定义要捕获的错误。指定错误代码（例如 ',
  'Define the error to throw. Specify an error code (e.g. ': '定义要抛出的错误。指定错误代码（例如 ',
  'Define the FEEL expression to evaluate and the variable to store the result in. ':
    '定义要评估的 FEEL 表达式以及存储结果的变量。',
  'Define the ID of the process to call (e.g. ': '定义要调用的流程的 ID（例如 ',
  'Define the name of the variable that will contain the error code.': '定义将包含错误代码的变量名。',
  'Define the name of the variable that will contain the error message.': '定义将包含错误消息的变量名。',
  'Define the name of the variable that will contain the escalation code.': '定义将包含升级代码的变量名。',
  'Define a boolean condition expression that determines when this sequence flow is taken. ':
    '定义布尔条件表达式，决定何时采用此顺序流。',
  'Define a collection of elements which will be activated when the ad-hoc subprocess is reached. ':
    '定义即席子流程到达时将激活的元素集合。',
  'Define an input collection expression that defines the collection to iterate over (e.g. ':
    '定义用于迭代的输入集合表达式（例如 ',
  'Define how to collect the outputs of the ad-hoc subprocess. The output collection variable stores the list of results; the output element expression defines what each element contributes. ':
    '定义如何收集即席子流程的输出。输出集合变量存储结果列表；输出元素表达式定义每个元素的贡献。',
  'Define static metadata passed to job workers alongside each job. Headers are not evaluated by the engine — use them for fixed worker configuration (e.g. ':
    '定义与每个作业一起传递给作业处理器的静态元数据。引擎不解析请求头——将其用于固定的处理器配置（例如 ',
  'Control the business ID set on a child process. If left empty, no business ID will be set. ':
    '控制子流程上设置的业务 ID。若留空，则不设置业务 ID。',
  'Control which variables from the called process are merged back into the parent scope. By default, all child variables are propagated; use output mappings to selectively return specific variables. ':
    '控制被调用流程中的哪些变量合并回父作用域。默认传播所有子变量；使用输出映射有选择地返回特定变量。',
  'If turned on, all variables from the child process instance will be propagated to the parent process instance.':
    '若开启，子流程实例的所有变量将传播到父流程实例。',
  'If turned on, all variables from the parent process instance will be propagated to the child process instance.':
    '若开启，父流程实例的所有变量将传播到子流程实例。',
  'Otherwise, only variables defined via input mappings will be propagated.':
    '否则，仅传播通过输入映射定义的变量。',
  'Otherwise, only variables defined via output mappings will be propagated.':
    '否则，仅传播通过输出映射定义的变量。',
  'Propagate all child process variables': '传播所有子流程变量',
  'Propagate all parent process variables': '传播所有父流程变量',
  'Propagate all variables': '传播所有变量',
  'Inherit from parent': '从父级继承',
  'Refers to the process variable name': '引用流程变量名',
  'This maps to the process definition key.': '这映射到流程定义标识。',
  'Process documentation': '流程文档',
  'Process variables': '流程变量',
  'Process ID': '流程编号',
  'Process name': '流程名称',
  'Ad-hoc subprocess documentation': '即席子流程文档',
  'Business rule task documentation': '业务规则任务文档',
  'Call activity documentation': '调用活动文档',
  'Called decision': '被调用的决策',
  'Called decision documentation': '被调用决策文档',
  'Called element': '被调用元素',
  'Send task documentation': '发送任务文档',
  'Service task documentation': '服务任务文档',
  'Receive task message documentation': '接收任务消息文档',
  'Execution listeners documentation': '执行监听器文档',
  'Input mappings documentation': '输入映射文档',
  'Output mappings documentation': '输出映射文档',
  'Task listeners documentation': '任务监听器文档',
  'User task documentation': '用户任务文档',
  'User task form documentation': '用户任务表单文档',
  'User task priority documentation': '用户任务优先级文档',
  'Task headers documentation': '任务请求头文档',
  'Job priority documentation': '作业优先级文档',
  'About conditional events.': '关于条件事件。',
  'A FEEL expression that determines whether the event should trigger. ': '决定事件是否触发的 FEEL 表达式。',
  'A specific point in time defined as ISO 8601 combined date and time representation.':
    '以 ISO 8601 日期时间组合表示定义的特定时间点。',
  'A time duration defined as ISO 8601 durations format.': '以 ISO 8601 时长格式定义的时间段。',
  'A cycle defined as ISO 8601 repeating intervals format, or a cron expression.':
    '以 ISO 8601 重复间隔格式定义的周期，或 cron 表达式。',
  'A cycle defined as ISO 8601 repeating intervals format.': '以 ISO 8601 重复间隔格式定义的周期。',
  '1 hour and 30 minutes': '1 小时 30 分钟',
  '14 days': '14 天',
  '15 seconds': '15 秒',
  'every 10 seconds, up to 5 times': '每 10 秒一次，最多 5 次',
  'every day, infinitely': '每天，无限循环',
  'every hour on the hour from 9-5 p.m. UTC Monday-Friday': 'UTC 周一至周五每天 9 点至 17 点整点每小时一次',
  'UTC plus 2 hours zone offset': 'UTC 加 2 小时时区偏移',
  'UTC time': 'UTC 时间',

  // ───────── 选项值 / 占位符 / 提示 ─────────
  '<custom type>': '<自定义类型>',
  '<empty>': '<空>',
  '<none>': '<无>',
  ' or ': ' 或 ',
  ', ': '， ',
  '). ': '）。',
  ') to identify the error. ': '）以识别错误。',
  ') to match a specific error, or leave empty to catch any error. ': '）以匹配特定错误，或留空以捕获任何错误。',
  'Custom type': '自定义类型',
  'Default value': '默认值',
  'Key': '键',
  'Label': '标签',
  'Value': '值',
  'Values': '值',
  'Type': '类型',
  'Format': '格式',
  'Source': '来源',
  'Target': '目标',
  'Source expression': '来源表达式',
  'Scope': '作用域',
  'Topic': '主题',
  'Code': '代码',
  'Code variable': '代码变量',
  'Result variable': '结果变量',
  'String': '字符串',
  'String or expression': '字符串或表达式',
  'boolean': '布尔',
  'long': '长整型',
  'enum': '枚举',
  'List': '列表',
  'List values': '列表值',
  'Map': '映射',
  'Map entries': '映射条目',
  'Map decision result': '映射决策结果',
  'Decision ID': '决策 ID',
  'Decision reference': '决策引用',
  'DMN decision': 'DMN 决策',
  'Implementation': '实现',
  'Implementation type': '实现类型',
  'Before': '之前',
  'After': '之后',
  'On': '开启',
  'Off': '关闭',
  'start': '开始',
  'end': '结束',
  'take': '采用',
  'complete': '完成',
  'active': '活动',
  'latest': '最新',
  'Local': '本地',
  'BPMN': 'BPMN',
  'CMMN': 'CMMN',
  'deployment': '部署',
  'Deployment binding': '部署绑定',
  'Latest binding': '最新绑定',
  'Version tag binding': '版本标签绑定',
  'Uses the most recent deployed resource.': '使用最新部署的资源。',
  'Uses the most recent deployed resource with the given version tag.': '使用具有给定版本标签的最新部署资源。',
  'Uses the resource found in the same deployment.': '使用同一部署中找到的资源。',
  'Version tag by which the called decision will be referenced.': '被调用决策所引用的版本标签。',
  'Version tag by which the called process will be referenced.': '被调用流程所引用的版本标签。',
  'Version tag by which the linked form will be referenced.': '所链接表单所引用的版本标签。',
  'Version tag by which this process can be referenced.': '此流程可被引用的版本标签。',
  'Number of days before this resource is being cleaned up. If specified, takes precedence over the engine configuration.':
    '清理此资源前的天数。若指定，则优先于引擎配置。',
  'Specifies the default priority for all jobs created by a process. Must be an integer. If no value is provided, the default value is 0. ':
    '指定流程创建的所有作业的默认优先级。必须为整数。若未提供值，默认值为 0。',
  'Specifies the priority of a job. Must be an integer. If no value is provided, the default value is 0. ':
    '指定作业的优先级。必须为整数。若未提供值，默认值为 0。',
  'Specifies the priority of a user task. Must be an integer between 0 and 100. If no value is provided, the default value is 50. ':
    '指定用户任务的优先级。必须为 0 到 100 之间的整数。若未提供值，默认值为 50。',
  'The due date as an EL expression (e.g. ${someDate}) or an ISO date (e.g. 2015-06-26T09:54:00).':
    '到期日为 EL 表达式（如 ${someDate}）或 ISO 日期（如 2015-06-26T09:54:00）。',
  'The follow up date as an EL expression (e.g. ${someDate}) or an ISO date (e.g. 2015-06-26T09:54:00).':
    '跟进日期为 EL 表达式（如 ${someDate}）或 ISO 日期（如 2015-06-26T09:54:00）。',
  'The number of times the engine tries executing this activity if a worker signals a failure. The default is three.':
    '当处理器报告失败时，引擎尝试执行此活动的次数。默认值为 3。',
  'Specify more than one group as a comma separated list.': '可使用逗号分隔的列表指定多个组。',
  'Specify more than one user as a comma separated list.': '可使用逗号分隔的列表指定多个用户。',
  'Specify more than one variable change event as a comma separated list. Variable change events are:':
    '可使用逗号分隔的列表指定多个变量变更事件。变量变更事件包括：',
  'Start typing "${}" to create an expression.': '输入 “${}” 以创建表达式。',
  'ID must be a valid QName.': '编号必须是有效的 QName。',
  'ID must be unique.': '编号必须唯一。',
  'ID must not be empty.': '编号不能为空。',
  'ID must not contain prefix.': '编号不能包含前缀。',
  'ID must not contain spaces.': '编号不能包含空格。',
  'JSON contains errors': 'JSON 包含错误',
  'Section contains an error': '分区包含错误',
  'Section contains edits': '分区包含修改',
  'Open documentation': '打开文档',
  'Open pop-up editor': '打开弹出编辑器',
  'Opened in editor': '已在编辑器中打开',
  'Learn more.': '了解更多。',
  'Learn how to define conditions.': '了解如何定义条件。',
  'Link': '链接',
  'Link a form created with the Camunda Forms editor. Submitting this form will start a new process instance. ':
    '链接使用 Camunda 表单编辑器创建的表单。提交此表单将启动一个新的流程实例。',
  'Link a form created with the Camunda Forms editor. To associate a custom form, application, or URL to the user task, specify an external reference. ':
    '链接使用 Camunda 表单编辑器创建的表单。要将自定义表单、应用或 URL 关联到用户任务，请指定外部引用。',
  'Link or embed a form created with the Camunda Forms editor. To associate a custom form, application, or URL to the user task, specify a form key. ':
    '链接或嵌入使用 Camunda 表单编辑器创建的表单。要将自定义表单、应用或 URL 关联到用户任务，请指定表单标识。',
  'Add custom key-value metadata to this element. Extension properties have no effect on process execution — they can be used to attach configuration visible for other consumers of the BPMN diagram. ':
    '为此元素添加自定义键值元数据。扩展属性不影响流程执行——可用于附加对 BPMN 图其他使用者可见的配置。',
  'Add custom logic that reacts to various events in the workflow execution life-cycle. ':
    '添加响应工作流执行生命周期中各种事件的自定义逻辑。',
  'Active elements': '活动元素',
  'Active elements collection': '活动元素集合',
  'Activity reference': '活动引用',
  'Case ref': '案例引用',
  'Constraints': '约束',
  'Headers': '请求头',
  'Tenant ID': '租户 ID',
  'Timeout': '超时',
  'timeout': '超时',
  'Wait for completion': '等待完成',
  'throw expression': '抛出表达式',
  'Throw expression': '抛出表达式',
  'FEEL expression': 'FEEL 表达式',
  'FEEL expression is mandatory': 'FEEL 表达式为必填项',
  'Unparsable FEEL expression.': '无法解析的 FEEL 表达式。',
  'collectEntries (List<Object>)': 'collectEntries（List<Object>）',
  'resultList (List<Map<String, Object>>)': 'resultList（List<Map<String, Object>>）',
  'singleEntry (TypedValue)': 'singleEntry（TypedValue）',
  'singleResult (Map<String, Object>)': 'singleResult（Map<String, Object>）',
  'Created in': '创建于',

  // ───────── @bpmn-io/properties-panel 内置组件文案 ─────────
  // 这些组件不走注入的 translate 服务，默认值为模块私有的 translateFallback，
  // 需配合 patches 中的 translateFallback 补丁才能命中本表的词条。
  // 列表分组头部悬停提示：单复数在运行期展开，两种形态都要登记
  'List contains {numOfItems} item': '列表包含 {numOfItems} 项',
  'List contains {numOfItems} items': '列表包含 {numOfItems} 项',
  // FEEL 动态值开关：三目运算在运行期展开为两种形态
  'Click to remove dynamic value with FEEL expression': '点击移除 FEEL 表达式动态值',
  'Click to set a dynamic value with FEEL expression': '点击设置 FEEL 表达式动态值',
  // Camunda 侧遗漏项
  'Participant Name': '参与者名称',
  // 监听器列表项标题：事件名 + {type} 占位，运行期拼成 「Start: {type}」等形式
  'Start: {type}': '开始：{type}',
  'End: {type}': '结束：{type}',
  'Cancel: {type}': '取消：{type}',
  'Before all: {type}': '全部之前：{type}',
  'Before each: {type}': '每次之前：{type}',
  'After each: {type}': '每次之后：{type}',
};

/** 小写索引，用于大小写/首尾空格不敏感的兜底匹配（bpmn-js 部分词条带尾部空格） */
const lowerIndex: Record<string, string> = {};
Object.keys(translations).forEach((key) => {
  const lower = key.trim().toLowerCase();
  if (!(lower in lowerIndex)) {
    lowerIndex[lower] = translations[key];
  }
});

/**
 * 自定义翻译函数：
 * 1) 先精确匹配，再按「去空格+小写」兜底匹配，都没命中则原样返回英文；
 * 2) 替换 {xxx} 占位符为实际值（占位符的取值若也在词条表中则一并翻译）。
 */
export function customTranslate(
  template: string,
  replacements?: Record<string, any>,
): string {
  const t = (template ?? '').trim();
  let result: string = translations[t] || lowerIndex[t.toLowerCase()] || template;

  if (replacements) {
    result = result.replace(/{([^}]+)}/g, (_match: string, key: string) => {
      const value = replacements[key];
      if (value === undefined || value === null) return `{${key}}`;
      const strValue = String(value);
      return translations[strValue] || lowerIndex[strValue.toLowerCase()] || strValue;
    });
  }

  return result;
}

/**
 * 覆盖 bpmn-js 的 translate 服务（didi 注入：以 value 形式提供函数）。
 */
const customTranslateModule: any = {
  translate: ['value', customTranslate],
};

/**
 * 兜底通道：`@bpmn-io/properties-panel` 的内置组件（Group / ListGroup / ListItem /
 * JsonEditorEntry / FEEL 相关等）**不使用**注入的 translate 服务，其 `translate`
 * 形参默认为该包内私有的 `translateFallback`，而上游 `PropertiesPanel` 既不接收也不
 * 向下透传 `translate`（详见 patches/@bpmn-io__properties-panel@3.54.1.patch）。
 *
 * 因此把本文件的中文词典挂到全局，由上述补丁中的 translateFallback 读取，
 * 使内置文案（创建 / 删除项 / 切换分区 / 列表包含 N 项 等）也能翻译。
 * 词典未命中时返回原文，行为与上游一致。
 */
(globalThis as any).__BPMN_ZH_TRANSLATE__ = customTranslate;

export default customTranslateModule;
